/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/9612eb2c-e5ec-40c7-812a-0f6822b93996 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int blinkingTime;
  bool switchOn;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"


const int ledPin = 2; //onboard LED Pin

void setup() {
  blinkingTime = 1000;
  // Initilize LED Pin as output
  pinMode(ledPin, OUTPUT);
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}
void loop() {
  ArduinoCloud.update();
  // Your code here 
  digitalWrite(ledPin, HIGH);
  delay(blinkingTime);
  
  //Turn LED off
  digitalWrite(ledPin, LOW);
  delay(blinkingTime);
  
  
}




/*
  Since Inte is READ_WRITE variable, onInteChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onInteChange()  {
  // Add your code here to act upon Inte change
}

/*

  Since SwitchOn is READ_WRITE variable, onSwitchOnChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onSwitchOnChange()  {
  // Add your code here to act upon SwitchOn change
}

/*
  Since BlinkingTime is READ_WRITE variable, onBlinkingTimeChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onBlinkingTimeChange()  {
  // Add your code here to act upon BlinkingTime change
}
